Support launching browser in WSL Ubuntu 18.04
AzureAD/microsoft-authentication-library-for-python pull request #333
Opened 2021-03-29 10:31 UTC by jiasli

Fix #332

The code is migrated from Azure CLI:

https://github.com/Azure/azure-cli/blob/3bff786b9e337aa35bb4cc64a09e5600a35663f8/src/azure-cli-core/azure/cli/core/util.py#L642-L648

```py
    if is_wsl():   # windows 10 linux subsystem
        try:
            # https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe
            # Ampersand (&) should be quoted
            return subprocess.call(['powershell.exe', '-Command', 'Start-Process "{}"'.format(url)])
        except OSError:  # WSL might be too old  # FileNotFoundError introduced in Python 3
            pass
```

`_browse` now tries `webbrowser.open` first. If that fails and WSL is detected, launch browser with `powershell.exe`.

As for why `powershell.exe` is preferred over `cmd.exe`, it is discussed in https://github.com/Azure/azure-cli/pull/12851.

2021-03-29 11:52 UTC, jiasli commented
`www-browser` internally also uses `powershell.exe`

https://github.com/wslutilities/wslu/blob/221e85457c01e92db675cc7b24a49dfcdfacc6a9/src/wslu-header#L156

```py
	"$(interop_prefix)$(sysdrive_prefix)"/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -NoProfile -NonInteractive –ExecutionPolicy Bypass -Command "[Console]::OutputEncoding = [System.Text.Encoding]::UTF8; [Console]::InputEncoding = [System.Text.Encoding]::GetEncoding($cp); $@"
```

But we can keep it simple.

2021-03-29 11:56 UTC, jiasli commented on msal/oauth2cli/authcode.py
> +                ['powershell.exe', '-NoProfile', '-Command', 'Start-Process "{}"'.format(auth_uri)])
`-NoProfile` is necessary (https://github.com/Azure/azure-cli/pull/15361).

2021-03-30 02:54 UTC, rayluo requested changes

2021-03-30 02:54 UTC, rayluo commented on msal/oauth2cli/authcode.py
> +    release = getattr(uname, 'release', None).lower()
These 2 lines did not feel right. The default value `None` won't have the `lower()` method. Let's use this chance to make it compatible with some [other versions of Python](https://docs.python.org/2.7/library/platform.html#platform.uname) which do not return uname as a namedtuple.

```suggestion
    platform_name = getattr(uname, 'system', uname[0]).lower()
    release = getattr(uname, 'release', uname[2]).lower()
```

2021-03-30 02:54 UTC, rayluo commented on tests/test_authcode.py
> +from unittest.mock import patch
Azure CLI as an application can move on to use newer version of Python, but MSAL as a library still tries to keep compatibility with older Python when possible.

Here, `mock` is not a built-in module in Python 2.7, so the [build actions are failing](https://github.com/AzureAD/microsoft-authentication-library-for-python/actions). I'd suggest either declare a test dependency of external `mock` when running on Python 2.7, or simply remove this test case. Seriously, for logic as simple as this pr, I do not think we have to rely on test case like this.

2021-03-30 15:55 UTC, merged